#!/bin/bash

if [ -e "defs" ]; then
    source defs
else
    #source bin/defs
    source $SAGE_LOCAL/lib/python/site-packages/onlinelab/bin/defs
fi

#cd $ROOT
cd $SAGE_LOCAL/lib/python2.6/site-packages/onlinelab/root

#PYTHONPATH=$PYTHONPATH $PYTHONPATH/bin/codenode-admin backend $*
PYTHONPATH=$SAGE_LOCAL/lib/python2.6/site-packages/onlinelab/base/codenode-unr
$PYTHONPATH/bin/codenode-admin backend $*

